In [8]:
%use kandy
%use dataframe

In [1]:
val a = 3

In [2]:
a

3

In [9]:
import de.jugda.knanogpt.core.tensor.Shape
import de.jugda.knanogpt.core.tensor.Tensor
import org.skainet.activations.relu
import org.skainet.dsl.sequential


import org.skainet.nn.Module
import org.skainet.nn.NamedParameter
import org.skainet.Summary
import org.skainet.summary


class SineNN(override val name: String="sin") : Module() {

    private val sineModule =  sequential{
        input(1)
        linear(16, "layer1") {
            activation = relu
        }
        linear(16, "layer2") {
            activation = relu
        }
        linear(1, "output_layer")
    }
    override val params: List<NamedParameter>
        get() = emptyList()
    override val modules: List<Module>
        get() = sineModule.modules

    override fun forward(input: Tensor): Tensor =
        sineModule.forward(input)
}

In [10]:
val model = SineNN()

In [11]:
val summary = Summary().summary(model, Shape())
summary

[NodeSummary(name=layer1, input=Shape: Dimensions = [], Size (Volume) = 1, output=Shape: Dimensions = [1 x 16], Size (Volume) = 16, params=32), NodeSummary(name=layer2, input=Shape: Dimensions = [1 x 16], Size (Volume) = 16, output=Shape: Dimensions = [1 x 16], Size (Volume) = 16, params=272), NodeSummary(name=output_layer, input=Shape: Dimensions = [1 x 16], Size (Volume) = 16, output=Shape: Dimensions = [1 x 1], Size (Volume) = 1, params=17)]

In [12]:
fun SineNN.of(value: Double): Tensor = this.forward(Tensor(Shape(1), listOf(value.toDouble()).toDoubleArray()))

In [13]:
import org.skainnet.io.named.ModelsNamedParamsUpdater
import org.skainnet.io.named.json.JsonNamedParamsLoader
import java.nio.file.Paths



val path = Paths.get("../SKaiNET-samples/src/main/resources/sinus_model_parameters.json")

ModelsNamedParamsUpdater(
    JsonNamedParamsLoader(
        path.toFile()
    )
).update(model)

In [14]:
print(model.of(Math.PI/2.0))

[1.0046458781631062]

## Plot

In [15]:
val x_values = List(100) { index ->
    (index / (100 - 1).toFloat()) * (PI / 2)
}

val y_values = List(100) { index ->
    sin(x_values[index])
}


val y_nn_values = List(100) { index ->
    model.of(x_values[index]).elements[0]
}

val error = List(100) { index ->
    abs(y_values[index] - y_nn_values[index])
}


val df = dataFrameOf(
    "y" to y_values + y_nn_values + error,
    "x" to x_values + x_values + x_values,
    "mode" to List(100) { "sin" } + List(100) { "nn" } + List(100) { "error" }
)

df

y,x,mode
"0,000000","0,000000",sin
"0,015866","0,015867",sin
"0,031728","0,031733",sin
"0,047582","0,047600",sin
"0,063424","0,063467",sin
"0,079250","0,079333",sin
"0,095056","0,095200",sin
"0,110838","0,111066",sin
"0,126592","0,126933",sin
"0,142315","0,142800",sin
"0,158001","0,158666",sin
"0,173648","0,174533",sin
"0,189251","0,190400",sin
"0,204807","0,206266",sin
"0,220311","0,222133",sin
"0,235759","0,237999",sin
"0,251148","0,253866",sin
"0,266474","0,269733",sin
"0,281733","0,285599",sin
"0,296920","0,301466",sin

In [16]:
df

y,x,mode
"0,000000","0,000000",sin
"0,015866","0,015867",sin
"0,031728","0,031733",sin
"0,047582","0,047600",sin
"0,063424","0,063467",sin
"0,079250","0,079333",sin
"0,095056","0,095200",sin
"0,110838","0,111066",sin
"0,126592","0,126933",sin
"0,142315","0,142800",sin
"0,158001","0,158666",sin
"0,173648","0,174533",sin
"0,189251","0,190400",sin
"0,204807","0,206266",sin
"0,220311","0,222133",sin
"0,235759","0,237999",sin
"0,251148","0,253866",sin
"0,266474","0,269733",sin
"0,281733","0,285599",sin
"0,296920","0,301466",sin

In [3]:
df.plot {
    line {
        x("x")
        y("y")
        color("mode") {
            scale = categorical("sin" to Color.PURPLE, "nn" to Color.ORANGE, "error" to Color.RED)
        }
        width = 1.5
    }
}

org.jetbrains.kotlinx.jupyter.exceptions.ReplCompilerException: Line_4.jupyter.kts (1:1 - 3) Unresolved reference: df
Line_4.jupyter.kts (2:5 - 9) Unresolved reference: line
Line_4.jupyter.kts (3:9 - 10) Unresolved reference: x
Line_4.jupyter.kts (4:9 - 10) Unresolved reference: y
Line_4.jupyter.kts (5:9 - 14) Unresolved reference: color
Line_4.jupyter.kts (6:13 - 18) Unresolved reference: scale
Line_4.jupyter.kts (6:21 - 32) Unresolved reference: categorical
Line_4.jupyter.kts (6:42 - 47) Unresolved reference: Color
Line_4.jupyter.kts (6:64 - 69) Unresolved reference: Color
Line_4.jupyter.kts (6:89 - 94) Unresolved reference: Color
Line_4.jupyter.kts (8:9 - 14) Unresolved reference: width